title = "StackExchange Configuration"

[owner]
name = "Foo bar"

[stackAPI]
client_id = "12345"
client_secret = "12345"
api_key = "12345"


[database]
host="redis"
port=6789
password="password"

[logging]
file=true
log_file="app.log"
log_level="DEBUG"

