title = "StackExchange Configuration"

[owner]
name = "Foo Bar"

# These are optional fields, if you don't provide stack exchange API credentials,
# the number of requests will be throttled. Read more here: https://api.stackexchange.com/docs
[API]
stack_client_id = ""
stack_client_secret = ""
stack_api_key = ""

# These are optional fields as well, if you want request caching you can hook up the application to a redis DB.
[database]
redis_host = ""
redis_port = ""
redis_password = ""

[logging]
log_to_file = false
log_filename = "stackexchange.log"
log_level = "DEBUG"

