#!/bin/sh

STAGED_PY_FILES=$(git diff --diff-filter=d --cached --name-only | grep -E '\.(py)$')

run_formatting_on_staged_py_files() {
    for file in $STAGED_PY_FILES; do
      echo $file
        poetry run black --line-length=120 $file
        poetry run isort --line-length=120 $file
    done
}

run_flake8_on_staged_py_files() {
    for file in $STAGED_PY_FILES; do
        poetry run flake8 $file

        if [ $? -ne 0 ]; then
            echo "Flake8 failed on staged file ${file}"
        fi
    done
}

run_formatting_on_staged_py_files
run_flake8_on_staged_py_files